CREATE SCHEMA `USR` DEFAULT CHARACTER SET utf8 ;

use USR;

CREATE TABLE `USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(64) NULL,
  `AGE` INT NULL,
  `REGISTER_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`));